"""correction

Revision ID: 95e89024b2b6
Revises: cc5169bc681e
Create Date: 2025-03-29 17:49:05.342199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95e89024b2b6"
down_revision: Union[str, None] = "cc5169bc681e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_providers_email", table_name="providers")
    op.drop_index("ix_providers_id", table_name="providers")
    op.drop_index("ix_providers_name", table_name="providers")
    op.drop_table("providers", cascade=True)
    op.drop_index("ix_evc_providers_id", table_name="evc_providers")
    op.drop_table("evc_providers", cascade=True)
    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_id", table_name="users")
    op.drop_index("ix_users_username", table_name="users")
    op.drop_table("users", cascade=True)
    op.add_column(
        "provider", sa.Column("category_provider_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "provider", "category_provider", ["category_provider_id"], ["id"]
    )
    op.drop_constraint(
        "role_provider_provider_id_fkey", "role_provider", type_="foreignkey"
    )
    op.create_foreign_key(None, "role_provider", "provider", ["provider_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "role_provider", type_="foreignkey")
    op.create_foreign_key(
        "role_provider_provider_id_fkey",
        "role_provider",
        "providers",
        ["provider_id"],
        ["id"],
    )
    op.drop_constraint(None, "provider", type_="foreignkey")
    op.drop_column("provider", "category_provider_id")
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "username", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "password", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
    )
    op.create_index("ix_users_username", "users", ["username"], unique=False)
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.create_table(
        "evc_providers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("role_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("evc_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("provider_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["evc_id"], ["evc.id"], name="evc_providers_evc_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["providers.id"], name="evc_providers_provider_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="evc_providers_pkey"),
    )
    op.create_index("ix_evc_providers_id", "evc_providers", ["id"], unique=False)
    op.create_table(
        "providers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("company", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("country", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "cost_usd",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("line", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="providers_pkey"),
    )
    op.create_index("ix_providers_name", "providers", ["name"], unique=False)
    op.create_index("ix_providers_id", "providers", ["id"], unique=False)
    op.create_index("ix_providers_email", "providers", ["email"], unique=False)
    # ### end Alembic commands ###
