"""initial

Revision ID: ab9276498644
Revises: 
Create Date: 2025-03-29 17:18:09.121548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9276498644'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entorno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entorno_id'), 'entorno', ['id'], unique=False)
    op.create_table('evc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('project', sa.String(length=60), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evc_id'), 'evc', ['id'], unique=False)
    op.create_table('evc_financial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evc_financial_id'), 'evc_financial', ['id'], unique=False)
    op.create_table('evc_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evc_providers_id'), 'evc_providers', ['id'], unique=False)
    op.create_table('evc_q',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('q', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evc_q_id'), 'evc_q', ['id'], unique=False)
    op.create_table('functional_leader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_functional_leader_id'), 'functional_leader', ['id'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_email'), 'providers', ['email'], unique=True)
    op.create_index(op.f('ix_providers_id'), 'providers', ['id'], unique=False)
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=True)
    op.create_table('technical_leader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_leader_id'), 'technical_leader', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technical_leader_id'), table_name='technical_leader')
    op.drop_table('technical_leader')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_index(op.f('ix_providers_id'), table_name='providers')
    op.drop_index(op.f('ix_providers_email'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_functional_leader_id'), table_name='functional_leader')
    op.drop_table('functional_leader')
    op.drop_index(op.f('ix_evc_q_id'), table_name='evc_q')
    op.drop_table('evc_q')
    op.drop_index(op.f('ix_evc_providers_id'), table_name='evc_providers')
    op.drop_table('evc_providers')
    op.drop_index(op.f('ix_evc_financial_id'), table_name='evc_financial')
    op.drop_table('evc_financial')
    op.drop_index(op.f('ix_evc_id'), table_name='evc')
    op.drop_table('evc')
    op.drop_index(op.f('ix_entorno_id'), table_name='entorno')
    op.drop_table('entorno')
    # ### end Alembic commands ###
