"""corrected evc_q

Revision ID: 05308acafa5e
Revises: 264b91949cb2
Create Date: 2025-04-16 21:15:11.115529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05308acafa5e"
down_revision: Union[str, None] = "264b91949cb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("evc_q", sa.Column("allocated_budget", sa.Float(), nullable=True))
    op.add_column("evc_q", sa.Column("allocated_percentage", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evc_q", "allocated_percentage")
    op.drop_column("evc_q", "allocated_budget")
    # ### end Alembic commands ###
