"""value_usd instead of value

Revision ID: 0930eb0c0181
Revises: ddab268b9a10
Create Date: 2025-04-22 08:07:54.620097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0930eb0c0181'
down_revision: Union[str, None] = None#'ddab268b9a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evc_financial', sa.Column('value_usd', sa.Float(), nullable=True))
    op.drop_column('evc_financial', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evc_financial', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('evc_financial', 'value_usd')
    # ### end Alembic commands ###
