"""initial migration

Revision ID: 2b67a4ede147
Revises: 
Create Date: 2025-04-22 17:17:20.077331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b67a4ede147'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_id'), 'app_user', ['id'], unique=False)
    op.create_index(op.f('ix_app_user_username'), 'app_user', ['username'], unique=True)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('functional_leader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_functional_leader_id'), 'functional_leader', ['id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_table('notification_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_table', sa.String(), nullable=False),
    sa.Column('condition_field', sa.String(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('comparison', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_rule_id'), 'notification_rule', ['id'], unique=False)
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_email'), 'provider', ['email'], unique=True)
    op.create_index(op.f('ix_provider_id'), 'provider', ['id'], unique=False)
    op.create_index(op.f('ix_provider_name'), 'provider', ['name'], unique=True)
    op.create_table('technical_leader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_leader_id'), 'technical_leader', ['id'], unique=False)
    op.create_table('app_user_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_category_id'), 'app_user_category', ['id'], unique=False)
    op.create_table('entorno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('technical_leader_id', sa.Integer(), nullable=True),
    sa.Column('functional_leader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['functional_leader_id'], ['functional_leader.id'], ),
    sa.ForeignKeyConstraint(['technical_leader_id'], ['technical_leader.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entorno_id'), 'entorno', ['id'], unique=False)
    op.create_table('evc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('technical_leader_id', sa.Integer(), nullable=True),
    sa.Column('functional_leader_id', sa.Integer(), nullable=True),
    sa.Column('entorno_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['entorno_id'], ['entorno.id'], ),
    sa.ForeignKeyConstraint(['functional_leader_id'], ['functional_leader.id'], ),
    sa.ForeignKeyConstraint(['technical_leader_id'], ['technical_leader.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evc_id'), 'evc', ['id'], unique=False)
    op.create_table('evc_q',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('q', sa.Integer(), nullable=False),
    sa.Column('evc_id', sa.Integer(), nullable=True),
    sa.Column('allocated_budget', sa.Float(), nullable=True),
    sa.Column('allocated_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['evc_id'], ['evc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evc_q_id'), 'evc_q', ['id'], unique=False)
    op.create_table('evc_financial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evc_q_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('concept', sa.String(length=100), nullable=True),
    sa.Column('value_usd', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['evc_q_id'], ['evc_q.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evc_financial_id'), 'evc_financial', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evc_financial_id'), table_name='evc_financial')
    op.drop_table('evc_financial')
    op.drop_index(op.f('ix_evc_q_id'), table_name='evc_q')
    op.drop_table('evc_q')
    op.drop_index(op.f('ix_evc_id'), table_name='evc')
    op.drop_table('evc')
    op.drop_index(op.f('ix_entorno_id'), table_name='entorno')
    op.drop_table('entorno')
    op.drop_index(op.f('ix_app_user_category_id'), table_name='app_user_category')
    op.drop_table('app_user_category')
    op.drop_index(op.f('ix_technical_leader_id'), table_name='technical_leader')
    op.drop_table('technical_leader')
    op.drop_index(op.f('ix_provider_name'), table_name='provider')
    op.drop_index(op.f('ix_provider_id'), table_name='provider')
    op.drop_index(op.f('ix_provider_email'), table_name='provider')
    op.drop_table('provider')
    op.drop_index(op.f('ix_notification_rule_id'), table_name='notification_rule')
    op.drop_table('notification_rule')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_functional_leader_id'), table_name='functional_leader')
    op.drop_table('functional_leader')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_app_user_username'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
