"""simplify_user_model

Revision ID: 30db9e622e95
Revises: e163f34c8d9b
Create Date: 2025-03-12 13:21:40.233824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "30db9e622e95"
down_revision: Union[str, None] = "e163f34c8d9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_providers_email", table_name="providers")
    op.drop_index("ix_providers_id", table_name="providers")
    op.drop_index("ix_providers_name", table_name="providers")
    op.drop_table("providers")
    op.add_column("evc", sa.Column("project", sa.String(length=60), nullable=False))
    op.alter_column("evc", "name", existing_type=sa.VARCHAR(length=60), nullable=False)
    op.drop_index("ix_evc_name", table_name="evc")
    op.drop_column("evc", "description")
    op.drop_column("evc", "status")
    op.alter_column(
        "technical_leader", "name", existing_type=sa.VARCHAR(length=80), nullable=True
    )
    op.alter_column(
        "technical_leader", "email", existing_type=sa.VARCHAR(length=80), nullable=True
    )
    op.create_index(
        op.f("ix_technical_leader_email"), "technical_leader", ["email"], unique=True
    )
    op.drop_column("technical_leader", "entry_date")
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "technical_leader",
        sa.Column(
            "entry_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_technical_leader_email"), table_name="technical_leader")
    op.alter_column(
        "technical_leader", "email", existing_type=sa.VARCHAR(length=80), nullable=False
    )
    op.alter_column(
        "technical_leader", "name", existing_type=sa.VARCHAR(length=80), nullable=False
    )
    op.add_column(
        "evc", sa.Column("status", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "evc", sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index("ix_evc_name", "evc", ["name"], unique=False)
    op.alter_column("evc", "name", existing_type=sa.VARCHAR(length=60), nullable=True)
    op.drop_column("evc", "project")
    op.create_table(
        "providers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("company", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("country", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "cost_usd",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("line", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="providers_pkey"),
    )
    op.create_index("ix_providers_name", "providers", ["name"], unique=False)
    op.create_index("ix_providers_id", "providers", ["id"], unique=False)
    op.create_index("ix_providers_email", "providers", ["email"], unique=False)
    # ### end Alembic commands ###
