"""is_admin and is_active fields

Revision ID: 3ea68883e6c0
Revises: 59a533baaf7b
Create Date: 2025-04-18 11:06:08.121199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea68883e6c0'
down_revision: Union[str, None] = '59a533baaf7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('app_user', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'is_active')
    op.drop_column('app_user', 'is_admin')
    # ### end Alembic commands ###
