"""user implementation

Revision ID: 4757818de78e
Revises: 05308acafa5e
Create Date: 2025-04-17 15:05:56.166371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4757818de78e'
down_revision: Union[str, None] = '05308acafa5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.add_column('app_user', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('app_user', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_constraint('app_user_username_key', 'app_user', type_='unique')
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_username'), 'app_user', ['username'], unique=True)
    op.drop_column('app_user', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_app_user_username'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.create_unique_constraint('app_user_username_key', 'app_user', ['username'])
    op.drop_column('app_user', 'password')
    op.drop_column('app_user', 'email')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
