"""Removed some items at provider model

Revision ID: 65ec10fae05c
Revises: b0d6316a128e
Create Date: 2025-04-15 16:23:48.249378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65ec10fae05c"
down_revision: Union[str, None] = "b0d6316a128e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provider", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "provider", sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
