"""add category_line table

Revision ID: 695fe8b8e35e
Revises: a80c6d877dcc
Create Date: 2025-04-20 17:15:45.369289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695fe8b8e35e'
down_revision: Union[str, None] = 'a80c6d877dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('category_line_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'provider', 'category_line', ['category_line_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider', type_='foreignkey')
    op.drop_column('provider', 'category_line_id')
    # ### end Alembic commands ###
