"""user implementation

Revision ID: 6be7b49d9938
Revises: 4757818de78e
Create Date: 2025-04-17 15:25:09.329594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be7b49d9938'
down_revision: Union[str, None] = '4757818de78e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user_category', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('app_user_category_app_user_id_fkey', 'app_user_category', type_='foreignkey')
    op.create_foreign_key(None, 'app_user_category', 'app_user', ['user_id'], ['id'])
    op.drop_column('app_user_category', 'app_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user_category', sa.Column('app_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'app_user_category', type_='foreignkey')
    op.create_foreign_key('app_user_category_app_user_id_fkey', 'app_user_category', 'app_user', ['app_user_id'], ['id'])
    op.drop_column('app_user_category', 'user_id')
    # ### end Alembic commands ###
