"""add rol field to user

Revision ID: 73fcc7c86535
Revises: 12be8cb8d034
Create Date: 2025-04-21 19:48:02.202272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73fcc7c86535'
down_revision: Union[str, None] = '12be8cb8d034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('rol', sa.String(length=20), nullable=False, server_default='consultor'))
    op.alter_column('app_user', 'rol', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'rol')
    # ### end Alembic commands ###
