"""Complete Database

Revision ID: a7f52f23af8b
Revises: e163f34c8d9b
Create Date: 2025-03-12 11:38:01.583471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7f52f23af8b"
down_revision: Union[str, None] = "e163f34c8d9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evc_q",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("q", sa.Integer(), nullable=False),
        sa.Column("allocated_budget", sa.Float(), nullable=False),
        sa.Column("evc_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["evc_id"],
            ["evc.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evc_q_id"), "evc_q", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evc_q_id"), table_name="evc_q")
    op.drop_table("evc_q")
    # ### end Alembic commands ###
