"""evc_financials relationship provider

Revision ID: a90c12197753
Revises: 95c705ef0673
Create Date: 2025-04-21 09:26:11.195027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90c12197753'
down_revision: Union[str, None] = '95c705ef0673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_email'), 'provider', ['email'], unique=True)
    op.create_index(op.f('ix_provider_id'), 'provider', ['id'], unique=False)
    op.create_index(op.f('ix_provider_name'), 'provider', ['name'], unique=True)
    op.drop_index('ix_providers_email', table_name='providers')
    op.drop_index('ix_providers_id', table_name='providers')
    op.drop_index('ix_providers_name', table_name='providers')
    op.drop_table('providers')
    op.add_column('evc_financial', sa.Column('provider_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'evc_financial', 'provider', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evc_financial', type_='foreignkey')
    op.drop_column('evc_financial', 'provider_id')
    op.create_table('providers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('line', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='providers_pkey')
    )
    op.create_index('ix_providers_name', 'providers', ['name'], unique=False)
    op.create_index('ix_providers_id', 'providers', ['id'], unique=False)
    op.create_index('ix_providers_email', 'providers', ['email'], unique=False)
    op.drop_index(op.f('ix_provider_name'), table_name='provider')
    op.drop_index(op.f('ix_provider_id'), table_name='provider')
    op.drop_index(op.f('ix_provider_email'), table_name='provider')
    op.drop_table('provider')
    # ### end Alembic commands ###
