"""Removed some items at provider model

Revision ID: b0d6316a128e
Revises: c3c712b75d77
Create Date: 2025-04-15 16:21:31.368491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d6316a128e'
down_revision: Union[str, None] = 'c3c712b75d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'cost_usd')
    op.drop_column('provider', 'line')
    op.drop_column('provider', 'country')
    op.drop_column('provider', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('provider', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('provider', sa.Column('line', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('provider', sa.Column('cost_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
