"""add description to evc

Revision ID: c3c712b75d77
Revises: beb62dc8a263
Create Date: 2025-04-15 11:21:49.368891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c712b75d77'
down_revision: Union[str, None] = 'beb62dc8a263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evc', sa.Column('description', sa.String(), nullable=True))
    op.add_column('evc', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_column('evc', 'project')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evc', sa.Column('project', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_column('evc', 'status')
    op.drop_column('evc', 'description')
    # ### end Alembic commands ###
