"""modifying evc_financial

Revision ID: ddab268b9a10
Revises: a90c12197753
Create Date: 2025-04-22 07:50:22.019608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddab268b9a10'
down_revision: Union[str, None] = 'a90c12197753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evc_financial', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('evc_financial', sa.Column('concept', sa.String(length=100), nullable=True))
    op.add_column('evc_financial', sa.Column('value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evc_financial', 'value')
    op.drop_column('evc_financial', 'concept')
    op.drop_column('evc_financial', 'created_at')
    # ### end Alembic commands ###
