"""Generate correct tables

Revision ID: e163f34c8d9b
Revises: 
Create Date: 2025-03-11 21:53:35.581462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e163f34c8d9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functional_leader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_functional_leader_id'), 'functional_leader', ['id'], unique=False)
    op.create_table('technical_leader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_leader_id'), 'technical_leader', ['id'], unique=False)
    op.create_table('entorno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('functional_leader_id', sa.Integer(), nullable=True),
    sa.Column('technical_leader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['functional_leader_id'], ['functional_leader.id'], ),
    sa.ForeignKeyConstraint(['technical_leader_id'], ['technical_leader.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entorno_id'), 'entorno', ['id'], unique=False)
    op.create_table('evc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('entorno_id', sa.Integer(), nullable=True),
    sa.Column('functional_leader_id', sa.Integer(), nullable=True),
    sa.Column('technical_leader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entorno_id'], ['entorno.id'], ),
    sa.ForeignKeyConstraint(['functional_leader_id'], ['functional_leader.id'], ),
    sa.ForeignKeyConstraint(['technical_leader_id'], ['technical_leader.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evc_id'), 'evc', ['id'], unique=False)
    op.create_index(op.f('ix_evc_name'), 'evc', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evc_name'), table_name='evc')
    op.drop_index(op.f('ix_evc_id'), table_name='evc')
    op.drop_table('evc')
    op.drop_index(op.f('ix_entorno_id'), table_name='entorno')
    op.drop_table('entorno')
    op.drop_index(op.f('ix_technical_leader_id'), table_name='technical_leader')
    op.drop_table('technical_leader')
    op.drop_index(op.f('ix_functional_leader_id'), table_name='functional_leader')
    op.drop_table('functional_leader')
    # ### end Alembic commands ###
